LongName: Wayne State University
Description: The Wayne State University WSU-GRID_ce2 cluster

ID: 10261
AddressLine1: 5925 Woodward Ave
City: Detroit

Country: US
State: MI
Zipcode: "48202"

Latitude: 45.359044
Longitude: -83.066546
